version: "3.1"

services:
  chatty-rest-api:
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongodb
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/chatty-database

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017