version: "3.1"

services:
  chatty-config-server:
    image:  hyness/spring-cloud-config-server
    hostname: chatty-service-discovery
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=https://github.com/fabianopaes/chatty-config-repo.git
    expose:
      - "8888"
    ports:
      - "8888:8888"
    networks:
      - microservices

  chatty-service-discovery:
    image:  springcloud/eureka
    hostname: chatty-service-discovery
    depends_on:
      - chatty-config-server
    links:
      - chatty-config-server
    expose:
      - "8761"
    ports:
      - "8761:8761"
    networks:
      - microservices

  chatty-rest-api:
    build: ./chatty-rest-api
    hostname: chatty-rest-api
    expose:
      - "8080"
    ports:
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/chatty-database
      - SPRING_PROFILES_ACTIVE=docker
    links:
      - chatty-config-server
      - chatty-service-discovery
    networks:
      - microservices

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
