version: "3.1"

services:
  chatty-rest-api:
    build: ./chatty-rest-api
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    expose:
      - "8080"
    ports:  
      - "8080:8080"
    depends_on:
      - mongodb
    environment:
      - DATABASE_URI=mongodb://mongodb:27017/chatty-database
      - EUREKA_CLIENT_ENABLED=false
    networks:
      - microservices

  mongodb:
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
      - microservices

networks:
  microservices:
    driver: bridge
